username: GitHub-CI
icon_url: https://octodex.github.com/images/femalecodertocat.png

pretext: Triggered via {{eventName}} by {{actor}} {{default action "action"}} {{ref}} `{{diffRef}}`
title: GitHub Actions
title_link: https://support.github.com

text: &text |
  *<{{workflowRunUrl}}|Workflow _{{workflow}}_ job _{{jobName}}_ triggered by _{{eventName}}_ is _{{jobStatus}}_>* for <{{refUrl}}|`{{ref}}`>
  {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{{description}}}{{/if}}
  {{#if payload.commits}}
  *Commits*
  {{#each payload.commits}}
  <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
  {{/each}}
  {{/if}}

fallback: |-
  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}

fields:
  - title: Job Steps
    value: "{{#each jobSteps}}{{icon this.outcome}} {{@key}}\n{{/each}}"
    short: false
  - title: Job Matrix
    value: "{{#each jobMatrix}}{{@key}}: {{this}}\n{{/each}}"
    short: false
  - title: Job Inputs
    value: "{{#each jobInputs}}{{@key}}: {{this}}\n{{/each}}"
    short: false
  - title: Workflow
    value: "<{{{workflowUrl}}}|{{workflow}}>"
    short: true
  - title: Git Ref
    value: "{{ref}} ({{refType}})"
    short: true
  - title: Run ID
    value: |-
      <{{workflowRunUrl}}|{{runId}}>
    short: true
  - title: Run Number
    value: "{{runNumber}}"
    short: true
  - title: Actor
    value: "{{actor}}"
    short: true
  - title: Job Status
    value: "{{jobStatus}}"
    short: true

blocks:
  # author
  - type: context
    elements:
    - type: image
      image_url: '{{{sender.avatar_url}}}'
      alt_text: '{{sender.login}}'
    - type: mrkdwn
      text: "*<{{sender.html_url}}|{{sender.login}}>*"

  # title
  - type: section
    text:
      type: mrkdwn
      text: |
        *<{{title_link}}|{{title}}>*

  # text
  - type: section
    text:
      type: mrkdwn
      text: *text
    accessory:
      type: button
      text:
        type: plain_text
        text: View
      value: workflow_run_{{runId}}
      url: '{{workflowRunUrl}}'
      action_id: button-action

  # fields
  - type: section
    fields:
    - type: mrkdwn
      text: |-
        *Job Steps*
        {{#each jobSteps}}{{#ifneq this.outcome 'skipped'}}{{icon this.outcome}}  {{@key}}
        {{/ifneq}}{{/each}}
  - type: section
    fields:
    - type: mrkdwn
      text: "*Workflow*\n<{{{workflowUrl}}}|{{workflow}}>"
    - type: mrkdwn
      text: "*Git Ref*\n{{ref}} ({{refType}})"
    - type: mrkdwn
      text: |-
        *Run ID*
        <{{workflowRunUrl}}|{{runId}}>
    - type: mrkdwn
      text: "*Run Number*\n{{runNumber}}"
    - type: mrkdwn
      text: "*Actor*\n{{actor}}"
    - type: mrkdwn
      text: "*Job Status*\n{{jobStatus}}"

  # footer
  - type: context
    elements:
    - type: image
      image_url: '{{footer_icon}}'
      alt_text: github
    - type: mrkdwn
      text: '{{{footer}}} | <!date^{{ts}}^{date_short_pretty} at {time}|{{ts}}>'

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: '#5DADE2'
  failure: '#884EA0'
  cancelled: '#A569BD'
  default: '#7D3C98'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'
