name: slack - GitHub Actions Slack integration
description: Notify Slack of GitHub Actions workflows, jobs and step status.
author: satterly
inputs:
  token:
    description: Slack API token
    required: false
  config:
    description: Configuration file
    required: false
    default: .github/slack.yml
  status:
    description: Specify success, failure, cancelled or a custom status
    required: true
  steps:
    description: Report on the status of individual steps
    required: false
  channel:
    description: Override default channel with different channel or username
    required: false
  message:
    description: Override message format for step
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: alert-circle
  color: red
